(FIX#58) Melhora Front e arruma responsividade
fga-eps-mds/2024.2-ARANDU-APP pull request #37
Opened 2024-12-11 04:57 UTC by dylancavalcante

# Descrição

Este *pull request* visa melhorar a responsividade do front-end da aplicação, garantindo que o layout seja adaptável a diferentes tamanhos de tela conforme previsto na *issue* fga-eps-mds/2024.2-ARANDU-DOC#58.

# Revisão

- [ ] Implementação do `SingleChildScrollView` para permitir o scroll em dispositivos móveis.
- [ ] Uso de `Expanded` para distribuir o espaço disponível entre os widgets.
- [ ] Ajuste de margens e paddings para garantir um layout flexível e responsivo.

# Checklist

- [ ] O conteúdo adicionado nesse PR segue o código de conduta do projeto;
- [ ] Foram seguidos os padrões estabelecidos no guia de contribuição;
- [ ] O conteúdo adicionado foi devidamente testado;
- [ ] O conteúdo do PR foi revisado por membro alheio ao mesmo;
- [ ] O conteúdo deste PR foi devidamente identado, comentado e documentado;
- [ ] Para conteúdos de documentação, foi adicionada tabela de versionamento aos artefatos.

2024-12-11 13:01 UTC, GabrielCostaDeOliveira requested changes
não ultiliza imags como bores e seu layout não está responsivo, 
![img](https://github.com/user-attachments/assets/52058e6e-3cd8-480c-b3d4-e615071a0d37)

2024-12-11 13:01 UTC, GabrielCostaDeOliveira commented on assets/images/Buttons1.png
Estamos utilizando o Material Design, e ele já define um monte de widgets prontos [veja os widgets](https://docs.flutter.dev/ui/widgets/material).

É muito melhor que você escolha algum deles e o adapte para o nosso caso.

Quando utilizamos um desses widgets, conseguimos mudar a cor do botão quando o aplicativo fica no tema escuro ou, se trocarmos o tema do aplicativo, esse widget já mudará automaticamente. Ou seja, a linha de desenvolvimento é evitar componentes[ ad-hoc](https://pt.stackoverflow.com/questions/505248/o-que-significa-ad-hoc-no-contexto-da-computa%C3%A7%C3%A3o).

2024-12-11 21:43 UTC, dylancavalcante commented on assets/images/Buttons1.png
Os botões foram substituídos por widgets documentados e todos os textos foram padronizados. Só estou com dificuldade de settar o botão _"começar"_ no canto **inferior direito** da tela visto que ele não obedece o comando _center.right_ na linha 210

2024-12-11 21:44 UTC, dylancavalcante commented
> Não utilize imagens como botões, e sua página não está responsiva.
> 
> ![img](https://private-user-images.githubusercontent.com/60332560/394753627-52058e6e-3cd8-480c-b3d4-e615071a0d37.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5NDk0NzUsIm5iZiI6MTczMzk0OTE3NSwicGF0aCI6Ii82MDMzMjU2MC8zOTQ3NTM2MjctNTIwNThlNmUtM2NkOC00ODBjLWIzZDQtZTYxNTA3MWEwZDM3LmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMVQyMDMyNTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jM2E1MmQ1MGE5NmQ2M2YzMTU1NzUzZjc1ZTMwZDM4ZTJkZDg4ODg0YzU5ZjQzZmVhMjI5NTUxNDAwZWZjNmI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9._GQIeeZ0sXD7RMEDZ1gLijHTXtF_zVdKlqWFeY13F_c)

Problemas resolvidos.

2024-12-12 19:52 UTC, GabrielCostaDeOliveira requested changes
Antes de tudo, resolva este conflito para fazer o merge

2024-12-12 22:43 UTC, dylancavalcante commented
> Antes de tudo, resolva este conflito para fazer o merge

Resolvido!

2024-12-13 13:51 UTC, GabrielCostaDeOliveira requested changes
A impressão é que você estava indo no caminho certo, mas o ChatGPT mais te atrapalhou do que ajudou. O código que ele produz é muito ruim.

2024-12-13 13:51 UTC, GabrielCostaDeOliveira commented on assets/images/Component2.png
Mano, essa bola laranja, veja se você consegue fazer ela em código Flutter, ou se consegue destacar essa bola em uma imagem SVG diferente. O problema é que, do jeito que ela está, ela não reage à mudança do tema

2024-12-13 13:51 UTC, GabrielCostaDeOliveira commented on lib/ui/onboarding/view/onboarding_view.dart
> +                              fontSize: 18,
Não use tamanhos de texto ad hoc; utilize apenas os tamanhos de texto definidos no Theme.

a cor secundária é um azul

```dart
Theme.of(context).colorScheme.secondary
```

2024-12-13 13:51 UTC, GabrielCostaDeOliveira commented on lib/ui/onboarding/view/onboarding_view.dart
> +                                MaterialStateProperty.resolveWith<Color?>(
Não utilize nada depreciado.

2024-12-13 13:51 UTC, GabrielCostaDeOliveira commented on lib/ui/onboarding/view/onboarding_view.dart
> +    return Scaffold(
esse método está muito grande, quebre ele em metodo monores, olhe como a view do login está, isso estava certo antes :(, pq vc tirou?

2024-12-13 13:51 UTC, GabrielCostaDeOliveira commented on lib/ui/onboarding/view/onboarding_view.dart
> -  Widget _buildNavigationButtons() {
oque vc tirou tava separadinho

2024-12-14 02:11 UTC, GabrielCostaDeOliveira requested changes
isualmente, a sua tela está perfeita, parabéns! 

Faltam apenas algumas correções para que ela fique pronta.

O nome do seu commit está errado, deveria ser

`fix(#58) Melhora Front e arruma responsividade`

mas vc colocou 

`(FIX#58) Melhora Front e arruma responsividade`

veja o [guia de contribuição](https://fga-eps-mds.github.io/2024.2-ARANDU-DOC/guias/guia_de_contribuicao/#commiting)

2024-12-14 02:36 UTC, dylancavalcante commented
> isualmente, a sua tela está perfeita, parabéns!
> 
> Faltam apenas algumas correções para que ela fique pronta.
> 
> O nome do seu commit está errado, deveria ser
> 
> `fix(#58) Melhora Front e arruma responsividade`
> 
> mas vc colocou
> 
> `(FIX#58) Melhora Front e arruma responsividade`
> 
> veja o [guia de contribuição](https://fga-eps-mds.github.io/2024.2-ARANDU-DOC/guias/guia_de_contribuicao/#commiting)

Resolvido!

2024-12-14 11:58 UTC, GabrielCostaDeOliveira requested changes
Nome do commit ainda está errado 

Deveria ser assim
`fix(#58) Melhora Front e arruma responsividade`

2024-12-16 12:19 UTC, GabrielCostaDeOliveira approved these changes
parabéns pelo trabalho a tela está perfeita

2024-12-16 15:28 UTC, merged